package rotp.ui.options;

public interface ISubUiKeys {
	// Level 0
	String COMBAT_ASTEROID_UI_KEY		= "COMBAT_ASTEROID";
	String COMBAT_TIMING_UI_KEY			= "COMBAT_TIMING";
	String COMBAT_XILMI_AI_UI_KEY		= "COMBAT_XILMI_AI";
	String COUNCIL_OPTIONS_UI_KEY		= "COUNCIL_OPTIONS";
	String FLAG_OPTIONS_UI_KEY			= "AUTO_FLAG";
	String GAME_DIFFICULTY_UI_KEY		= "GAME_DIFFICULTY";
	String HELP_AND_ADVICE_UI_KEY		= "HELP_AND_ADVICE";
	String IRONMAN_LITTLE_UI_KEY		= "IRONMAN_LITTLE";
	String NEW_OPTIONS_BETA_UI_KEY		= "NEW_OPTIONS_BETA";
	String NEW_RULES_BETA_UI_KEY		= "NEW_RULES_BETA";
	String SHIELD_ANIMATION_UI_KEY		= "SHIELD_ANIMATIONS";
	String SPY_OPTIONS_UI_KEY			= "SPY_OPTIONS";
	String VISUAL_OPTIONS_UI_KEY		= "VISUAL_OPTIONS";
	String WEAPON_ANIMATION_UI_KEY		= "WEAPON_ANIMATIONS";


	
	// Level 1
	String DIPLOMACY_OPTIONS_UI_KEY		= "DIPLOMACY_OPTIONS";
	String GAME_AUTOMATION_UI_KEY		= "GAME_AUTOMATION";
	String SHIP_COMBAT_RULES_UI_KEY		= "SHIP_COMBAT_RULES";
	String SHIP_COMBAT_SETTINGS_UI_KEY	= "SHIP_COMBAT_SETTINGS";

	// Level 2
	String COMBAT_OPTIONS_UI_KEY		= "COMBAT_OPTIONS";
	
	// Level Top
	String COMMON_OPTIONS_UI_KEY		= "COMMON_OPTIONS";
	String RULES_OPTIONS_UI_KEY			= "RULES_OPTIONS";
	String SETTINGS_OPTIONS_UI_KEY		= "SETTINGS_OPTIONS";
	

}
